#!/bin/bash
# output-env.sh — Extract Bicep deployment outputs and generate .env file
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RESOURCE_GROUP="rg-multi-agent-ops-assistant"

echo "  Extracting deployment outputs..."
OUTPUTS=$(az deployment group show \
  --resource-group "$RESOURCE_GROUP" \
  --name main \
  --query properties.outputs \
  -o json)

FOUNDRY_ENDPOINT=$(echo "$OUTPUTS" | jq -r '.foundryEndpoint.value')
SEARCH_ENDPOINT=$(echo "$OUTPUTS" | jq -r '.searchEndpoint.value')
SQL_CONNECTION_STRING=$(echo "$OUTPUTS" | jq -r '.sqlConnectionString.value')
ACR_LOGIN_SERVER=$(echo "$OUTPUTS" | jq -r '.acrLoginServer.value')
KEY_VAULT_URI=$(echo "$OUTPUTS" | jq -r '.keyVaultUri.value')
STORAGE_ACCOUNT_NAME=$(echo "$OUTPUTS" | jq -r '.storageAccountName.value')

cat > "$PROJECT_ROOT/.env" << EOF
# Multi-Agent Ops Assistant — Environment Variables
# Generated by output-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

AZURE_AI_PROJECT_ENDPOINT=$FOUNDRY_ENDPOINT
AZURE_AI_MODEL_DEPLOYMENT_NAME=gpt-4o
AZURE_AI_SEARCH_ENDPOINT=$SEARCH_ENDPOINT
KNOWLEDGE_BASE_NAME=ops-assistant-kb
SQL_CONNECTION_STRING=$SQL_CONNECTION_STRING
ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER
KEY_VAULT_URI=$KEY_VAULT_URI
STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME
DEFAULT_STORE_ID=STORE-001
EOF

echo "  ✅ .env file written to $PROJECT_ROOT/.env"
