"""
Tools for demand forecasting — mobile order queue and historical patterns.
Plain functions — schemas auto-generated by Agent Framework / Foundry SDK.
"""
from datetime import datetime, timedelta, timezone
from tools.db import managed_connection
from config.settings import DEFAULT_STORE_ID


def get_mobile_order_queue(store_id: str = DEFAULT_STORE_ID) -> dict:
    """
    Get the current mobile order pipeline — pending orders scheduled
    for the next 30 minutes. Useful for detecting incoming surges.
    """
    with managed_connection() as conn:
        cursor = conn.cursor()

        now = datetime.now(timezone.utc)
        window_end = now + timedelta(minutes=30)

        cursor.execute("""
            SELECT DrinkType, COUNT(*) as Count,
                   MIN(ScheduledTime) as Earliest,
                   MAX(ScheduledTime) as Latest
            FROM dbo.MobileOrderQueue
            WHERE StoreId = ? AND Status = 'pending'
              AND ScheduledTime BETWEEN ? AND ?
            GROUP BY DrinkType
        """, store_id, now, window_end)

        orders_by_type = {}
        total_pending = 0
        for row in cursor.fetchall():
            orders_by_type[row.DrinkType] = {
                "count": row.Count,
                "earliest": row.Earliest.isoformat(),
                "latest": row.Latest.isoformat(),
            }
            total_pending += row.Count

        yesterday_start = now - timedelta(days=1)
        yesterday_end = yesterday_start + timedelta(minutes=30)
        cursor.execute("""
            SELECT COUNT(*) as Count
            FROM dbo.MobileOrderQueue
            WHERE StoreId = ? AND ScheduledTime BETWEEN ? AND ?
        """, store_id, yesterday_start, yesterday_end)

        yesterday_count = cursor.fetchone().Count

    trend = (
        "increasing"
        if total_pending > yesterday_count * 1.2
        else "decreasing" if total_pending < yesterday_count * 0.8 else "stable"
    )
    dominant_type = (
        max(orders_by_type, key=lambda k: orders_by_type[k]["count"])
        if orders_by_type
        else "none"
    )

    return {
        "store_id": store_id,
        "window": f"next 30 minutes ({now.strftime('%H:%M')} - {window_end.strftime('%H:%M')})",
        "total_pending_orders": total_pending,
        "orders_by_type": orders_by_type,
        "dominant_type": dominant_type,
        "yesterday_same_window": yesterday_count,
        "trend": trend,
        "surge_detected": total_pending > yesterday_count * 1.5,
    }


def get_demand_forecast(
    store_id: str = DEFAULT_STORE_ID,
    minutes_ahead: int = 30,
) -> dict:
    """
    Get demand forecast for the next N minutes based on historical patterns
    and current mobile order pipeline. Combines historical averages with
    real-time mobile order data for a blended prediction.
    """
    with managed_connection() as conn:
        cursor = conn.cursor()

        now = datetime.now(timezone.utc)

        # Single query with subqueries instead of three separate round-trips
        cursor.execute("""
            SELECT
                (SELECT AVG(OrdersPerHour)
                 FROM dbo.StationMetrics
                 WHERE StoreId = ? AND DATEPART(HOUR, Timestamp) = ?
                   AND DATEPART(WEEKDAY, Timestamp) = DATEPART(WEEKDAY, SYSUTCDATETIME())
                   AND Timestamp > DATEADD(WEEK, -4, SYSUTCDATETIME())
                ) AS HistAvg,
                (SELECT COUNT(*)
                 FROM dbo.LiveOrders
                 WHERE StoreId = ? AND OrderTime > DATEADD(MINUTE, -15, SYSUTCDATETIME())
                ) AS RecentOrders,
                (SELECT COUNT(*)
                 FROM dbo.MobileOrderQueue
                 WHERE StoreId = ? AND Status = 'pending'
                   AND ScheduledTime BETWEEN SYSUTCDATETIME()
                       AND DATEADD(MINUTE, ?, SYSUTCDATETIME())
                ) AS PendingMobile
        """, store_id, now.hour, store_id, store_id, minutes_ahead)

        row = cursor.fetchone()
        historical_avg = row.HistAvg if row.HistAvg else 0
        recent = row.RecentOrders
        current_run_rate = recent * 4
        pending_mobile = row.PendingMobile

    forecast_hourly = round(
        historical_avg * 0.4
        + current_run_rate * 0.4
        + (pending_mobile * (60 / minutes_ahead)) * 0.2
    )
    forecast_in_window = round(forecast_hourly * (minutes_ahead / 60))

    return {
        "store_id": store_id,
        "forecast_window_minutes": minutes_ahead,
        "historical_avg_hourly": round(historical_avg),
        "current_run_rate_hourly": current_run_rate,
        "pending_mobile_in_window": pending_mobile,
        "forecasted_orders_in_window": forecast_in_window,
        "forecasted_hourly_rate": forecast_hourly,
        "confidence": (
            "high"
            if abs(current_run_rate - historical_avg) < historical_avg * 0.3
            else "medium"
        ),
        "surge_risk": pending_mobile
        > (historical_avg * (minutes_ahead / 60) * 0.5),
    }
