"""
Tools for retrieving real-time POS and store operations data.
Plain functions — schemas auto-generated by Agent Framework / Foundry SDK.
"""
from datetime import datetime, timezone
from tools.db import managed_connection
from config.settings import DEFAULT_STORE_ID


def get_store_metrics(store_id: str = DEFAULT_STORE_ID) -> dict:
    """
    Get current real-time store performance metrics including wait times,
    order counts, throughput, and hourly pace vs target.
    Use this when the manager asks 'how are we doing' or wants a status update.
    """
    with managed_connection() as conn:
        cursor = conn.cursor()

        cursor.execute("""
            SELECT Station, OrdersPerHour, CapacityPct, StaffCount, AvgWaitSecs,
                   ActiveOrders, PendingMobileOrders
            FROM dbo.vw_CurrentStoreStatus
            WHERE StoreId = ?
        """, store_id)

        stations = {}
        total_orders_per_hour = 0
        for row in cursor.fetchall():
            stations[row.Station] = {
                "orders_per_hour": row.OrdersPerHour,
                "capacity_pct": float(row.CapacityPct),
                "staff_count": row.StaffCount,
                "avg_wait_secs": row.AvgWaitSecs,
                "active_orders": row.ActiveOrders,
                "pending_mobile_orders": row.PendingMobileOrders,
            }
            total_orders_per_hour += row.OrdersPerHour

        now = datetime.now(timezone.utc)
        cursor.execute("""
            SELECT TOP 1 TargetOrders FROM dbo.HourlyTargets
            WHERE StoreId = ? AND HourOfDay = ? AND DayOfWeek = ?
        """, store_id, now.hour, now.weekday())

        target_row = cursor.fetchone()
        if not target_row:
            cursor.execute("""
                SELECT TOP 1 TargetOrders FROM dbo.HourlyTargets
                WHERE StoreId = ? AND HourOfDay = ?
            """, store_id, now.hour)
            target_row = cursor.fetchone()
        hourly_target = target_row.TargetOrders if target_row else 95

        total_weighted_wait = 0
        total_station_orders = 0
        for s in stations.values():
            total_weighted_wait += s["avg_wait_secs"] * s["orders_per_hour"]
            total_station_orders += s["orders_per_hour"]
        overall_avg_wait = (
            round(total_weighted_wait / total_station_orders)
            if total_station_orders > 0
            else 0
        )

    pace_pct = (
        round((total_orders_per_hour / hourly_target * 100), 1)
        if hourly_target > 0
        else 0
    )

    return {
        "store_id": store_id,
        "timestamp": now.isoformat(),
        "stations": stations,
        "total_orders_per_hour": total_orders_per_hour,
        "hourly_target": hourly_target,
        "pace_vs_target_pct": pace_pct,
        "overall_avg_wait_secs": overall_avg_wait,
        "total_active_orders": sum(
            s.get("active_orders", 0) or 0 for s in stations.values()
        ),
        "status": (
            "on_track"
            if pace_pct >= 90
            else "behind" if pace_pct >= 70 else "critical"
        ),
    }


def get_order_mix(store_id: str = DEFAULT_STORE_ID) -> dict:
    """
    Get the current order mix breakdown (hot vs cold vs food, in-store vs mobile).
    Use this to understand what types of orders are dominating.
    """
    with managed_connection() as conn:
        cursor = conn.cursor()

        # Single UNION ALL query instead of two separate round-trips
        cursor.execute("""
            SELECT 'drink' AS dimension, DrinkType AS category, COUNT(*) AS cnt
            FROM dbo.LiveOrders
            WHERE StoreId = ? AND OrderTime > DATEADD(MINUTE, -30, SYSUTCDATETIME())
            GROUP BY DrinkType
            UNION ALL
            SELECT 'channel' AS dimension, OrderType AS category, COUNT(*) AS cnt
            FROM dbo.LiveOrders
            WHERE StoreId = ? AND OrderTime > DATEADD(MINUTE, -30, SYSUTCDATETIME())
            GROUP BY OrderType
        """, store_id, store_id)

        drink_mix = {}
        channel_mix = {}
        total = 0
        for row in cursor.fetchall():
            if row.dimension == "drink":
                drink_mix[row.category] = row.cnt
                total += row.cnt
            else:
                channel_mix[row.category] = row.cnt

    drink_pct = {
        k: round(v / total * 100, 1) if total > 0 else 0
        for k, v in drink_mix.items()
    }

    return {
        "store_id": store_id,
        "period": "last_30_minutes",
        "drink_type_counts": drink_mix,
        "drink_type_percentages": drink_pct,
        "channel_counts": channel_mix,
        "total_orders": total,
        "dominant_type": max(drink_mix, key=drink_mix.get) if drink_mix else "none",
    }
