"""
Tools for staffing data and station throughput analysis.
Plain functions — schemas auto-generated by Agent Framework / Foundry SDK.
"""
from tools.db import managed_connection
from config.settings import DEFAULT_STORE_ID


def get_station_throughput(store_id: str = DEFAULT_STORE_ID) -> dict:
    """
    Get throughput and capacity data for each station (hot bar, cold bar, food).
    Includes current utilization percentage and staff count per station.
    Use this to identify which station is the bottleneck.
    """
    with managed_connection() as conn:
        cursor = conn.cursor()

        cursor.execute("""
            SELECT Station, OrdersPerHour, CapacityPct, StaffCount, AvgWaitSecs
            FROM dbo.vw_CurrentStoreStatus
            WHERE StoreId = ?
        """, store_id)

        stations = {}
        bottleneck = None
        max_capacity = 0

        for row in cursor.fetchall():
            station_data = {
                "orders_per_hour": row.OrdersPerHour,
                "capacity_pct": float(row.CapacityPct),
                "staff_count": row.StaffCount,
                "avg_wait_secs": row.AvgWaitSecs,
                "is_overloaded": float(row.CapacityPct) > 100,
            }
            stations[row.Station] = station_data

            if float(row.CapacityPct) > max_capacity:
                max_capacity = float(row.CapacityPct)
                bottleneck = row.Station

    return {
        "store_id": store_id,
        "stations": stations,
        "bottleneck_station": bottleneck,
        "bottleneck_capacity_pct": max_capacity,
        "has_bottleneck": max_capacity > 100,
    }


def get_staffing_positions(store_id: str = DEFAULT_STORE_ID) -> dict:
    """
    Get current staffing assignments — who is working at which station.
    Use this to recommend specific staff moves.
    """
    with managed_connection() as conn:
        cursor = conn.cursor()

        cursor.execute("""
            SELECT EmployeeName, Station, ShiftStart, ShiftEnd
            FROM dbo.StaffAssignments
            WHERE StoreId = ? AND IsActive = 1
            ORDER BY Station, EmployeeName
        """, store_id)

        staff_by_station = {}
        all_staff = []
        for row in cursor.fetchall():
            station = row.Station
            if station not in staff_by_station:
                staff_by_station[station] = []
            staff_entry = {
                "name": row.EmployeeName,
                "shift_start": row.ShiftStart.isoformat(),
                "shift_end": row.ShiftEnd.isoformat(),
            }
            staff_by_station[station].append(staff_entry)
            all_staff.append({**staff_entry, "station": station})

    return {
        "store_id": store_id,
        "staff_by_station": staff_by_station,
        "total_staff_on_floor": len(all_staff),
        "all_staff": all_staff,
    }


def _normalize_station(name: str) -> str:
    """Map display names ('Cold Bar', 'Hot Bar', 'Food Prep') to DB keys."""
    _MAP = {
        "cold bar": "cold_bar",
        "hot bar": "hot_bar",
        "food prep": "food",
        "food": "food",
        "cold_bar": "cold_bar",
        "hot_bar": "hot_bar",
    }
    return _MAP.get(name.strip().lower(), name.strip())


def move_staff_to_station(
    employee_name: str,
    new_station: str,
    store_id: str = DEFAULT_STORE_ID,
) -> dict:
    """
    Move a staff member to a different station by updating their assignment
    in the database. Returns confirmation with the old and new station.
    IMPORTANT: If success is False, do NOT say 'Done'. Report the error.
    """
    import logging
    _log = logging.getLogger(__name__)

    # Normalize station name so 'Cold Bar' → 'cold_bar' etc.
    new_station = _normalize_station(new_station)

    try:
        with managed_connection() as conn:
            cursor = conn.cursor()

            cursor.execute("""
                SELECT AssignmentId, Station
                FROM dbo.StaffAssignments
                WHERE StoreId = ? AND EmployeeName = ? AND IsActive = 1
            """, store_id, employee_name)

            row = cursor.fetchone()
            if not row:
                return {
                    "success": False,
                    "error": f"FAILED: No active assignment found for '{employee_name}' in store {store_id}.",
                }

            old_station = _normalize_station(row.Station)
            assignment_id = row.AssignmentId

            if old_station == new_station:
                return {
                    "success": False,
                    "error": f"FAILED: {employee_name} is already at {new_station}. No move needed.",
                }

            # ── Critical: update the assignment + normalize names ──
            cursor.execute("""
                UPDATE dbo.StaffAssignments SET Station = ? WHERE AssignmentId = ?
            """, new_station, assignment_id)

            # Also fix any other records that have non-canonical station names
            # (e.g. 'Cold Bar' from previous moves) so COUNT is accurate
            for canonical in ("hot_bar", "cold_bar", "food"):
                cursor.execute("""
                    UPDATE dbo.StaffAssignments
                    SET Station = ?
                    WHERE StoreId = ? AND IsActive = 1
                      AND LOWER(REPLACE(Station, ' ', '_')) = ?
                      AND Station != ?
                """, canonical, store_id, canonical, canonical)

            # COMMIT the assignment change immediately so it persists
            # even if the optional StationMetrics updates below fail
            conn.commit()
            _log.info("Staff assignment committed: %s → %s", employee_name, new_station)

            # ── Verify the change persisted ──
            cursor.execute("""
                SELECT Station FROM dbo.StaffAssignments WHERE AssignmentId = ?
            """, assignment_id)
            verify = cursor.fetchone()
            if not verify or _normalize_station(verify.Station) != new_station:
                actual = _normalize_station(verify.Station) if verify else "unknown"
                return {
                    "success": False,
                    "error": f"FAILED: Move did not persist. {employee_name} is still at {actual}.",
                }

            # ── Optional: update StationMetrics (non-critical) ──
            try:
                for station in (old_station, new_station):
                    cursor.execute("""
                        SELECT COUNT(*) AS cnt
                        FROM dbo.StaffAssignments
                        WHERE StoreId = ? AND Station = ? AND IsActive = 1
                    """, store_id, station)
                    new_count = cursor.fetchone().cnt

                    cursor.execute("""
                        SELECT TOP 1 StaffCount, CapacityPct, AvgWaitSecs
                        FROM dbo.StationMetrics
                        WHERE StoreId = ? AND Station = ?
                        ORDER BY Timestamp DESC
                    """, store_id, station)
                    metric = cursor.fetchone()
                    if metric and metric.StaffCount and metric.StaffCount > 0:
                        ratio = metric.StaffCount / max(new_count, 1)
                        new_capacity = round(float(metric.CapacityPct) * ratio, 2)
                        new_wait = round(
                            (metric.AvgWaitSecs or 0) * ratio
                        )

                        cursor.execute("""
                            UPDATE dbo.StationMetrics
                            SET StaffCount = ?, CapacityPct = ?, AvgWaitSecs = ?
                            WHERE StoreId = ? AND Station = ?
                              AND Timestamp = (
                                  SELECT MAX(Timestamp) FROM dbo.StationMetrics
                                  WHERE StoreId = ? AND Station = ?
                              )
                        """, new_count, new_capacity, new_wait,
                             store_id, station, store_id, station)

                conn.commit()
            except Exception as exc:
                _log.warning(
                    "StationMetrics update failed (non-critical, assignment already saved): %s",
                    exc,
                )

            return {
                "success": True,
                "employee": employee_name,
                "old_station": old_station,
                "new_station": new_station,
                "message": f"{employee_name} moved from {old_station} to {new_station}",
            }
    except Exception as exc:
        _log.error("move_staff_to_station failed: %s", exc, exc_info=True)
        return {
            "success": False,
            "error": f"FAILED: {exc}",
        }
